In [1]:
print("This noteboook is a python crash course")

This noteboook is a python crash course


In [2]:
print(1+1)

2


In [3]:
(1+2)

3

In [4]:
(3-2)

1

In [5]:
(3*5)

15

In [6]:
(10/5)

2.0

In [7]:
(6+9*3+3)

36

In [8]:
6 % 2

0

In [9]:
9 % 2

1

In [10]:
6 ** 2

36

In [11]:
13 // 2 

6

In [12]:
13 / 2

6.5

In [13]:
age = 18
age

18

In [14]:
age = 18
name = 'Srinivas'
gender = 'male'

In [15]:
age,name,gender = 18,'Srnivas','gender'

In [16]:
blood_type = 'O+ve'

In [17]:
x = 7
y = 3
z = x/y
print(z)

2.3333333333333335


In [18]:
type(x)

int

In [19]:
type(y)

int

In [20]:
type(z)

float

In [21]:
int(7/3.5)

2

In [22]:
w=int(3.7)

In [23]:
w

3

In [24]:
some_float = float(3)
print(some_float)

3.0


In [25]:
name = 'Srinivas'
print(name)
print(type(name))

Srinivas
<class 'str'>


In [26]:
name = "Srinivas"
print(name)
print(type(name))

Srinivas
<class 'str'>


In [27]:
dailogue = "Srinivas said "yo!" to which the dude replied wassup! dude!!!"
print(dialogue)

SyntaxError: invalid syntax (<ipython-input-27-0c8fe5802bfc>, line 1)

In [28]:
dialogue = 'Srinivas said "yo!" to which the dude replied wassup! dude!!!'
print(dialogue)

Srinivas said "yo!" to which the dude replied wassup! dude!!!


In [29]:
dialogue_1 = 'Srinivas said you're crazy!'
print(dialogue_1)

SyntaxError: invalid syntax (<ipython-input-29-157f8891f8dd>, line 1)

In [30]:
dialogue_1 = 'Srinivas said you\'re crazy!'
print(dialogue_1)

Srinivas said you're crazy!


In [31]:
segment_one='I\am 18'
segment_two = 'years old'
full = segment_one+" "+segment_two+" "
print(full*5)
print(len(full))

Im 18 years old Im 18 years old Im 18 years old Im 18 years old Im 18 years old 
17


In [32]:
earth_is_flat=True
earth_is_round=False

In [33]:
compare = 1>3
print(compare)

False


In [34]:
#logical operators -> and,or,not
compare_1 = 1<2 or 3>5
print(compare_1)

True


In [35]:
movie_title = 'Harry Potter and the Prisoner of Azkaban'
movie_title.upper()

'HARRY POTTER AND THE PRISONER OF AZKABAN'

In [36]:
movie_title.lower()

'harry potter and the prisoner of azkaban'

In [37]:
movie_title.count('a') #number of times the letter a shows

4

In [38]:
names = ['John','Jane','Joe']
print(names[0])
print(names[1])
print(names[2])

John
Jane
Joe


In [39]:
random_datatypes_of_list = ['True',True,1,1.434,'Srinivas']
print(random_datatypes_of_list)

['True', True, 1, 1.434, 'Srinivas']


In [40]:
length = len(random_datatypes_of_list)

In [41]:
print(length)

5


In [42]:
print(random_datatypes_of_list[length-1])

Srinivas


In [43]:
print(random_datatypes_of_list[-1])

Srinivas


In [44]:
print(random_datatypes_of_list[-2])

1.434


In [45]:
print(random_datatypes_of_list[-3])

1


In [46]:
ordered_numbers = [0,1,2,3,4,5,6,7,8,9,10]
print(ordered_numbers[2:10])
print(ordered_numbers)

[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
print(ordered_numbers[:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [48]:
print(ordered_numbers[:len(ordered_numbers)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [49]:
print(ordered_numbers[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [50]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [51]:
print(list(range(0,50,3)))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]


In [52]:
print(list(range(50,0,-3)))

[50, 47, 44, 41, 38, 35, 32, 29, 26, 23, 20, 17, 14, 11, 8, 5, 2]


In [53]:
show_title =  'game of thrones'
show_title[2:]

'me of thrones'

In [54]:
months = ['January','February','March']
print('June' in months)

False


In [55]:
print('January' in months)


True


In [56]:
print('Feb' not in months)

True


In [57]:
grocery_list = ['Banana','apple','Oranges']
grocery_list[2] = ['Mangoes']
print(grocery_list) #mutuable

['Banana', 'apple', ['Mangoes']]


In [58]:
misspelled_word='smert'
misspelled_word[2] = 'a'
print(misspelled_word) #not mutiable

TypeError: 'str' object does not support item assignment

In [ ]:
name='Ameer'
other_name = name
name = 'John'
print(name)
print(other_name)

In [ ]:
books = ['The Catcher in the Rye' , "The Mist" , 'Lord of the Rings']
more_books = books
books[0] = 'A song of ice and fire'
print(books[0])
print(more_books)

In [ ]:
""""
len()-> returns the length of the passed argument
max()-> return the maximum value in the passed argument
min() -> return the minimum value in the passed argument
''.join() -> joins all the elements of the list and returns it.
format(_) -> it fills the {} with the given format specifier in a order
append() -> add a new element to the existing list or any other mutuable datatype
sorted() -> sorts the list from lowest to highest.

In [59]:
strings= ["a","e","c"]
max(strings)

'e'

In [60]:
'_'.join(strings)

'a_e_c'

In [61]:
print('This person is {} ,{} and {}'.format('tall','slim','skinny'))


This person is tall ,slim and skinny


In [62]:
months=['Jan','Feb','Mar']
months.append('Apr')

In [63]:
print(months)

['Jan', 'Feb', 'Mar', 'Apr']


In [64]:
numbers= [4,3,7,4]
len(numbers)

4

In [65]:
sorted(numbers)

[3, 4, 4, 7]

In [67]:
"thr" in "the goof"

False

In [ ]:
Lists : Mutable ordered sequence of elements.
Tuples : Immutable ordered sequence of elements.
Sets : Mutable,unordered , unique sequence of elements.

In [69]:
traits = ('tall','slim','blond')
height = traits[0]
build = traits[1]
print(height,build)

tall slim


In [70]:
height , build,hair = traits

In [76]:
duplicate_numbers = [1,1,2,2,3,3]
unique_number = set(duplicate_numbers)
print(unique_number)

{1, 2, 3}


In [80]:
unique_number.add(4)
print(unique_number)

{1, 2, 3, 4}


In [81]:
unique_number.append(4)
print(unique_number)

AttributeError: 'set' object has no attribute 'append'

In [83]:
inventory = {'bananas' : 1.29, 'apples' : 1.82,'papayas' : 1.39}
print(inventory['bananas'])

1.29


In [84]:
print(inventory)

{'bananas': 1.29, 'apples': 1.82, 'papayas': 1.39}


In [85]:
inventory['bananas'] = 2.99
print(inventory)

{'bananas': 2.99, 'apples': 1.82, 'papayas': 1.39}


In [86]:
bananas_price = inventory.get('bananas')
print(bananas_price)

2.99


In [87]:
print(inventory.get('strawberries'))

None


In [88]:
print('papayas' in inventory)

True


In [54]:
grocery_items = {'bananas' : { 'price' : 2.99, 'country of origin' : 'Guatamela'},
                'apples' : {'price':1.29, 'country of origin': 'united Kingdom'},
                 'papayas' : {'price' : 2.39,'country of origin':'Costa Rica'}}

In [55]:
print(grocery_items['apples'])

{'price': 1.29, 'country of origin': 'united Kingdom'}


In [57]:
print(grocery_items['apples']['country of origin'])

united Kingdom


In [60]:
item = 'brussel sprouts'
if item in grocery_items:
    print("Found the items")
else:
    print("Error 404")
    grocery_items.update({item:2.99})

Error 404


In [61]:
if item in grocery_items:
    print("Hello")

Hello


In [63]:
item,price = 'tomatoes',4.45
if item in grocery_items:
    print('found the',item)
else:
    print('could not find the',item)
    grocery_items.update({item:2.99})
    print('just added the item, here is the updated grocery list',grocery_items)

found the tomatoes


In [64]:
reynolds_number = 5000
if 2000 < reynolds_number <10000:
    print('flow regime is transistional')
if reynolds_number > 2000 and reynolds_number <10000:
    print('flow is transsitional')
if reynolds_number <= 2000 or reynolds_number >= 10000:
    print('flow is not transistional')

flow regime is transistional
flow is transsitional


In [68]:
numbers = ['1','2','3','4','5']
for i in numbers:
    print(i)

TypeError: can only concatenate str (not "int") to str

In [69]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [72]:
names = ['hillary','diana','brian']
for index in range(len(names)):
    names[index] = names[index].title()

In [73]:
print(names)

['Hillary', 'Diana', 'Brian']


In [74]:
movies = {'Titanic' : 1997, 'Finding Nemo':2003}

for(key,value) in movies.items():
    print('The movie {}, was made in {}'.format(key,value))

The movie Titanic, was made in 1997
The movie Finding Nemo, was made in 2003


In [3]:
random_number = 20
while random_number <= 30:
    print(random_number)
    random_number+=1

20
21
22
23
24
25
26
27
28
29
30


In [9]:
numbers = list(range(0,10))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
for number in numbers:
    if number % 2 != 0:
        continue
    print(number)
        
         

0
2
4
6
8


In [15]:
def rectangle_area(length,width):
    return length*width
def square_area(length,width):
    print(length*width)

In [16]:
print(rectangle_area(2,3))
square_area(3,3)
                    

6
9


In [19]:
number = 3 #Global Variable
def random_function():
    name = 'Bill' #Local Variable
    print(number)
random_function()
    

3


In [22]:
def sample_function():
    """
    This function is for this purpose and this is called a docstring.
    """
    return ("Docstring is the description of the function")

In [27]:
numbers = list(range(1,6))
def even_or_odd(number):
    return number%2==0
print(list(filter(even_or_odd,numbers)))

[2, 4]


In [31]:
numbers = [1,2,3,4,5]
print(list(filter(lambda number : number %2 ==0 , numbers)))

[2, 4]


In [32]:
 ages = [5, 12, 17, 18, 24, 32]

def myFunc(x):
  if x < 18:
    return True
  else:
    return False

adults = filter(myFunc, ages)

for x in adults:
  print(x)

5
12
17


In [33]:
numbers1 = list((1,'jib'))
print(numbers1)


[1, 'jib']


In [34]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum=[]

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
    

In [37]:
import numpy as np
array_two = np.arange(1,4)
print(array_two)

[1 2 3]


In [38]:
array_two = np.arange(1,4) ** 2
print(array_two)

[1 4 9]


In [39]:
array_three = np.arange(1,4)**3
print(array_three)

[ 1  8 27]


In [40]:
print(array_two+array_three)

[ 2 12 36]


In [43]:
np.power(np.array([1,2,3]),4)

array([ 1, 16, 81], dtype=int32)

In [44]:
sample_array = np.array([1,2,3])

In [45]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [47]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

In [48]:
np.cos(sample_array)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [50]:
w = np.linspace(1,10,50)
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [2]:
import numpy as np
t = np.linspace(1,10)
print(t)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [5]:
import numpy as np

x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([y,z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]]
(2, 3)


In [6]:
multi_array[1,2]

2

In [10]:
x = np.arange(3,6)
y = np.arange(4,7)
z = np.arange(5,8)
multi_array = np.array([x,y,z])
print(multi_array)
print(multi_array.shape)

[[3 4 5]
 [4 5 6]
 [5 6 7]]
(3, 3)


In [12]:
print(multi_array.dtype)

int32


In [14]:
"""
x = np.arange(3,6)
y = np.arange(4,7)
z = np.arange(5,8)
multi_array = np.array([x,y,z],dtype = np.int16)
print(multi_array)
print(multi_array.shape)

[[3 4 5]
 [4 5 6]
 [5 6 7]]
(3, 3)


In [1]:
import numpy as np
x = np.arange(1,10)

In [2]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [3]:
print(x[2:7])

[3 4 5 6 7]


In [4]:
print(x[2:7:2])

[3 5 7]


In [5]:
print(x[:7])

[1 2 3 4 5 6 7]


In [1]:
import numpy as np
x=np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [2]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
import numpy as np
x=np.arange(18).reshape(2,3,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [4]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
x[2,1]

7

In [6]:
import numpy as np
x=np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [7]:
x[1,1,1]

10

In [10]:
x[1,0:2,0:3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
x[1,:2,:3:2]

array([[ 6,  8],
       [ 9, 11]])

In [12]:
comparison_operation = x>5
print(comparison_operation)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [13]:
print(x>5)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [15]:
x[comparison_operation]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [16]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [17]:
x.max()

17

In [18]:
x.min()

0

In [19]:
# ravel() -> takes a multi-dimensional array as an input and returns a single-dimensional array as an output

In [20]:
ravelled_array = x.ravel()
print(ravelled_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [21]:
flattened_array = x.flatten()
print(flattened_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [23]:
ravelled_array = x.ravel()
ravelled_array[2] = 10000000
print(ravelled_array)

[       0        1 10000000        3        4        5        6        7
        8        9       10       11       12       13       14       15
       16       17]


In [24]:
print(x)

[[[       0        1 10000000]
  [       3        4        5]]

 [[       6        7        8]
  [       9       10       11]]

 [[      12       13       14]
  [      15       16       17]]]


In [25]:
ravelled_array = x.ravel()
ravelled_array[2] = 2
print(ravelled_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [27]:
flattened_array = x.flatten()
flattened_array[2] = 100000
print(flattened_array)
print("          ")
print(x)

[     0      1 100000      3      4      5      6      7      8      9
     10     11     12     13     14     15     16     17]
          
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [28]:
y = np.arange(9)
y.shape = [3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
print(y.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [31]:
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [32]:
print(np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [37]:
np.zeros((6,) , dtype=int)

array([0, 0, 0, 0, 0, 0])

In [38]:
np.zeros((2,3) , dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [40]:
np.ones((6,) , dtype=int)

array([1, 1, 1, 1, 1, 1])

In [42]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
np.random.rand(3,3)

array([[0.68628583, 0.26610996, 0.68785664],
       [0.35056838, 0.13153591, 0.78161065],
       [0.82885378, 0.38730791, 0.43605078]])

In [46]:
mat_a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [47]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [48]:
mat_a*mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [49]:
product = np.matmul(mat_a,mat_b)
product

matrix([[ 29, -16],
        [ 38,   6]])

In [51]:
"""
mat_a = np.array([0,3,5,5,5,2]).reshape(2,3)
mat_a
mat_b = np.array([3,4,3,-2,4,-2]).reshape(3,2)
mat_b
"""

'\nmat_a = np.array([0,3,5,5,5,2]).reshape(2,3)\nmat_a\nmat_b = np.array([3,4,3,-2,4,-2]).reshape(3,2)\nmat_b\n'

In [52]:
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [54]:
x = np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [55]:
y = np.arange(4,8).reshape(2,2)
print(y)

[[4 5]
 [6 7]]


In [56]:
z = np.hstack((x,y))

In [58]:
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [60]:
a = np.arange(8).reshape(4,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [61]:
b = np.vstack((x,a))
print(b)
print(b.shape)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
(6, 2)


In [63]:
w =np.concatenate((x,y),axis =0)
print(w)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [65]:
z = np.hstack((x,y))
print(z == w)

False


<ipython-input-65-0e29b4963dfb>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(z == w)


In [66]:
depth_stack = np.dstack((x,y))
print(depth_stack)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [67]:
print(depth_stack.shape)

(2, 2, 2)
